### ISSUE TITLE
Not showing any devices!

### ISSUE THREAD

**Issue by myinnos** [Microsoft/project-rome#1]
Project is Interesting! I started working on this.

These are steps i did as of now 
**1**. Pulled **Android project-rome** from [HERE](https://github.com/Microsoft/project-rome/tree/master/Project%20Rome%20for%20Android%20(preview%20release)/sample)
**2**. Created app called **romanapp** in [Developer Account](https://apps.dev.microsoft.com)
**3**. Replaced **CLIENT_ID** with My CLIENT_ID [HERE #29](https://github.com/Microsoft/project-rome/blob/master/Project%20Rome%20for%20Android%20(preview%20release)/sample/app/src/main/java/com/microsoft/romanapp/MainActivity.java)

Authentication process done well! I logged in with Microsoft [LIVE](http://live.com) Account  

> **But its now showing any devices** 

Let me know any thing i **Missed** out 👎

**Comment by darkorm** [comment]
First things to check:

Is the Windows 10 pc you are discovering on the 1607 release or newer? (Settings App -> System -> About)

Is the account signed in to the PC associated with the same MSA account used on the Android device? (Settings App -> Accounts -> Email & app accounts)

**Comment by myinnos** [comment]
Perfect 👍 Loved It! But Login flow is Webview 👎 Need SDK for login flow!

**Comment by cmknox** [comment]
Thanks for the feedback!
