### ISSUE TITLE
Firebase dynamic links & 3rd party apps for AppUriHandlers 

### ISSUE THREAD

**Issue by bezysoftware** [Microsoft/project-rome#16]
Is it possible to use AppUriHandlers for Firebase dynamic links? Those links look like this: https://xyz.app.goo.gl/?link=....

The thing is I obviously cannot put any files to the root of https://xyz.app.goo.gl because that's not my domain..

Also 3rd party apps cannot take advantage of AppUriHandlers due to the requirement to have the json file on web root

**Comment by juanoviedoms** [comment]
Hello,

Does the Firebase dynamic link redirect to a website you own (i.e. a web server that has the JSON file)?

We currently don't support 3rd party apps in AppUriHandlers. You have to own both the website and app to take advantage of the feature at the moment.

Thanks.

**Comment by bezysoftware** [comment]
It does redirect to a website i own. But it's that going to help me in any way? Once the firebase link gets to the browser, the system won't be able to intercept the redirected uri, right?

**Comment by bezysoftware** [comment]
And the firebase dynamic link doesn't support addresses such as https://abcd.app.goo.gl/my-json-file (or whatever the name of the file should be), it only support ls query paramaters after the base address

**Comment by bezysoftware** [comment]
Also trying to use https://xyz.app.goo.gl/windows-app-web-link isn't going to work, because that's not a valid address. Google has a custom url shortener, which creates links like http://xyz.app.goo.gl/TxwUY but as far as I know it's an automated process, I cannot tell it to create a link with windows-app-web-link in the url

**Comment by juanoviedoms** [comment]
Hello,

Sorry for the delay in my response. That is correct, since we don't know where the shortened link points to we don't support AppUriHandlers in that situation. 

Correct, it won't work for the 2nd case either. I will look into this and see if there is anything we could do, but at this point we only support direct links to the supported/registered website.

Thanks.

**Comment by bezysoftware** [comment]
Any update on this? Still not supported?

**Comment by cmknox** [comment]
@bezysoftware no, no updates here
