### ISSUE TITLE
UnsatisfiedLinkError on xamarin sample

### ISSUE THREAD

**Issue by a-iafrate** [Microsoft/project-rome#19]
Hi,

if i launch the xamarin sample i obtain this error, i have tried on emulator and phisical devices with android 6 and 7, all works only on an old Samsung with android 5.1, if i try with other new devices i have this error
Thanks in advance

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/ConnectedDevices.Xamarin-1/base.apk"],nativeLibraryDirectories=[/data/app/ConnectedDevices.Xamarin-1/lib/x86_64, /data/app/ConnectedDevices.Xamarin-1/base.apk!/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libcdp_sdk.so"
05-16 17:42:27.156 E/AndroidRuntime( 2738): 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
05-16 17:42:27.156 E/AndroidRuntime( 2738): 	at java.lang.System.loadLibrary(System.java:1076)
05-16 17:42:27.156 E/AndroidRuntime( 2738): 	at com.microsoft.connecteddevices.PlatformInternal.<clinit>(PlatformInternal.java:19)
05-16 17:42:27.156 E/AndroidRuntime( 2738): 	at com.microsoft.connecteddevices.Platform$1.onDone(Platform.java:87)
05-16 17:42:27.156 E/AndroidRuntime( 2738): 	at com.microsoft.connecteddevices.Platform$OAuthWebAccountProvider.invokeCallbackOnDone(Platform.java:188)
05-16 17:42:27.156 E/AndroidRuntime( 2738): 	at com.microsoft.connecteddevices.Platform$OAuthWebAccountProvider.fetchAccessTokensAndCid(Platform.java:250)
05-16 17:42:27.156 E/AndroidRuntime( 2738): 	at com.microsoft.connecteddevices.Platform$OAuthWebAccountProvider$FetchTokensWithAuthCodeTask.run(Platform.java:355)
05-16 17:42:27.156 E/AndroidRuntime( 2738): 	at java.util.Timer$TimerImpl.run(Timer.java:284)
05-16 17:42:27.340 E/Surface ( 2738): getSlotFromBufferLocked: unknown buffer: 0x7fe2e6c1f630
05-16 17:42:29.917 I/Process ( 2738): Sending signal. PID: 2738 SIG: 9
`

**Comment by a-iafrate** [comment]
i have compiled the version 0.4.0 of Microsoft.ConnectedDevices.Xamarin.Droid.dll from updated source but the problem is here

**Comment by cmknox** [comment]
Thanks a-iafrate.  We've created a bug and are currently investigating.

**Comment by bbowman** [comment]
@a-iafrate Thanks for the report. I was able to reproduce this locally and will look into it.
