### ISSUE TITLE
Unique ID of current device

### ISSUE THREAD

**Issue by mghiasi75** [Microsoft/project-rome#22]
Is there any way to find the Unique ID of the current device (the ID which other instances of the app will see in their device list) in UWP?

**Comment by cmknox** [comment]
Hey mghiasi75 - At this time it is not possible to get the unique ID of the current device.

**Comment by mghiasi75** [comment]
@cmknox Is this the case in current version of Android/Xamarin Rome SDK too?

**Comment by cmknox** [comment]
@mghiasi75 that is correct.

**Comment by mghiasi75** [comment]
Thanks.
