### ISSUE TITLE
iOS Sample - Need to specify where client id is applied

### ISSUE THREAD

**Issue by bmitchell287** [Microsoft/project-rome#25]
In the readme you mention that we'll have to create a registration, but there's no mention of client id placement in the sample (AuthenticationViewController.m). There's also a pre-existing app id bound to the project regardless:

- (NSString*)appId
{
    // Change to your own app's MSA Client ID
    return @"8a284efa-414b-445e-8710-0fabde940942";
}

**Comment by PatrickFarley** [comment]
I don't see the confusion - users will replace the client ID in the sample with the client ID they get from registering. 

However, it might not be a good idea to hard-code an ID into the sample. @cmknox , @ajpeacock0 Thoughts?

**Comment by bmitchell287** [comment]
The confusion doesn’t come from replacing the existing ID, it comes from where to put it in the first place. The readme only mentions that you need to register but doesn’t mention the location of the app ID/client ID  (AuthenticationViewController.m), and it’s statically assigned deep in that class.  Maybe a quick note saying it should be applied in that view controller?

**Comment by bmitchell287** [comment]
The confusion doesn’t come from replacing the existing ID, it comes from where to put it in the first place. The readme only mentions that you need to register but doesn’t mention the location of the app ID/client ID  (AuthenticationViewController.m), and it’s statically assigned deep in that class.  Maybe a quick note saying it should be applied in that view controller? Thx.

**Comment by PatrickFarley** [comment]
Oh I see. I'll get that note added, thanks

**Comment by bmitchell287** [comment]
Thanks Patrick.
