### ISSUE TITLE
Native Windows Applications (WinForms/WPF)

### ISSUE THREAD

**Issue by cinatic** [Microsoft/project-rome#26]
Hello,

is it possible to register native Window Applications as "devices" with windows components or can i do it with the REST API/graph?

I can see in the graph api that there are "list device" and "send command" calls but it seems that something like "register device" is missing. How am i suppused to register something as a "device"?

Thanks and best regards

**Comment by sphenry** [comment]
@cinatic Windows registers devices when the user associates a Microsoft Account with the machine. Once a machine is registered, it can be enumerated using either the native WinRT API or from MS Graph. 

Any application (WinForms/WPf/WinForms) can be launched cross-device if it supports a 'scheme' (i.e. via LaunchUri). Only UWP or Desktop Bridge apps can be hosts for AppServices.

**Comment by cinatic** [comment]
hi @sphenry,

thanks for your response. Sounds good (doesn't work... lol no *scnr*). 

1. Is yet every pc added as device when i am logged in or only with latest creators update?
2. I tried it on an updated machine, i logged in and logged also in to graph explorer. then i tried get request for ...beta/me/devices and get a 500 error "unknown error", any idea?
3. Sorry i am bit confused about AppServices, this means the remote communication? w/o AppServices it will not work, right?

**Comment by sphenry** [comment]
@cinatic ,
1. Every PC with at least version1607 installed 
2. It's hard to say without more details. Did you have the correct OAuth scopes?
3. App Services are a mechanism to do rich communication between app. More info [here](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/communicate-with-a-remote-app-service). For simple communication, you might be able to get by with passing data as part of the URI launch

**Comment by cinatic** [comment]
2. You are right, i need to enable the scopes in the graph explorer

thanks for the information, i think this is an interesting project
