### ISSUE TITLE
Local account

### ISSUE THREAD

**Issue by mghiasi75** [Microsoft/project-rome#27]
When a user uses a local account, Rome APIs does not show any devices. Is there any way to allow user to sign-in in the app (but keep local account, the same way users can login into Groove, Store, etc. in a local account) so Rome APIs work?

**Comment by cmknox** [comment]
@mghiasi75 you can only use the local account if you connect the MSA to that account.  

You can do this on Windows:  Settings -> Accounts -> Email & App accounts -> Accounts used by other apps -> Add a Microsoft account.

If you are attempting a cross user scenario, using the RemoteSystemSession APIs, and there is not a connected MSA, you should be able to discover devices.

**Comment by mghiasi75** [comment]
So, how can I detect if there is a MSA connected to account or not? (So if not, show a message to user with instructions) 
Currently, the RemoteSystemWatcher just never detects a device if it's a local account.

**Comment by cmknox** [comment]
The Project Rome APIs do not support this.  However, I believe this is available on Windows using WAM (WebAccountManager APIs).  https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.provider.webaccountmanager
