### ISSUE TITLE
Not correct CDRemoteSystemStatus of discovered devices

### ISSUE THREAD

**Issue by revolutionkpi** [Microsoft/project-rome#29]
In delefate method
`-(void)remoteSystemDiscoveryManager:(nonnull CDRemoteSystemDiscoveryManager*)discoveryManager didFind:(nonnull CDRemoteSystem*)remoteSystem`

We get a `CDRemoteSystem` device. Its status `CDRemoteSystemStatus` is always `CDRemoteSystemStatusUnknown`. How can I check if device is available for `CDRemoteSystemConnectionRequest`?

**Comment by cmknox** [comment]
@revolutionkpi is this the same as issue #30 ?

**Comment by revolutionkpi** [comment]
Hi, no it is not the same. In this issue I get a list of available CDRemoteSystem systems with wrong status.
In an issue #30 I get wrong result for request when opens Uri on remove device for the first time.

**Comment by cmknox** [comment]
@revolutionkpi we have identified this issue as a bug.  Thanks so much for reporting.

**Comment by revolutionkpi** [comment]
I have just moved to 0.12.0 SDK and it works fine. Thanks.
