### ISSUE TITLE
License!

### ISSUE THREAD

**Issue by myinnos** [Microsoft/project-rome#3]
Can i use this project personally? 

Am planning to do Open source project using 

```
repositories {
    maven {
        url "https://projectrome.bintray.com/maven"
    }
}

dependencies { 
    compile(group: 'com.microsoft.connecteddevices', name: 'connecteddevices-core-armv7', version: '0.1.0', ext: 'aar', classifier: 'externalRelease') 
    compile(group: 'com.microsoft.connecteddevices', name: 'connecteddevices-sdk-armv7', version: '0.1.0', ext: 'aar', classifier: 'externalRelease') 
}
```

The project is like accessing PC browser through Android app 
Example : opining [www.bing.com](www.bing.com) from App

**Comment by myinnos** [comment]
Assigned as a `question`,  But who will answer this `question` ?

**Comment by cmknox** [comment]
Apologies for the delay.  I'm working with our attorney to get an answer to your question.  Should be today.  I appreciate your patience.

On Feb 16, 2017, at 3:17 AM, Prabhakar Thota <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned as a question, But who will answer this question ?

**Comment by myinnos** [comment]
Thanks you! Please Let me know as soon as **possible** 👍

**Comment by cmknox** [comment]
Thanks for your patience.

We are using the MIT license for the binaries hosted on Bintray.  The MIT license is a broad license which allows the user to use the software in any manner as long as they comply with the terms (personal or commercial).

**Comment by myinnos** [comment]
WOW! [MIT License](https://opensource.org/licenses/MIT)

 Thank you! I can use this [project ](https://github.com/Microsoft/project-rome/tree/master/Project%20Rome%20for%20Android%20(preview%20release)/sample) now

I am going to do one open source project along with  **play store**(not for commercial purpose) app!

Hope am exception more features from [this](https://github.com/Microsoft/project-rome/tree/master/Project%20Rome%20for%20Android%20(preview%20release)/sample) project! All the best 🥇

**Comment by cmknox** [comment]
Sounds great, we are excited to see your app using our platform.  Keep the feedback coming!
