### ISSUE TITLE
CDRemoteSystemConnectionRequest to device that is connected via cloud return CDRemoteLauncherUriStatusRemoteSystemUnavailable

### ISSUE THREAD

**Issue by revolutionkpi** [Microsoft/project-rome#30]
`CDRemoteSystemConnectionRequest` to device that is connected via cloud returns status `CDRemoteLauncherUriStatusRemoteSystemUnavailable`. In result request succesfully opens Uri on remove device. How can I detect a success result for `CDRemoteSystemConnectionRequest` in this case?

**Comment by cmknox** [comment]
@revolutionkpi CDRemoteLauncherUriStatusRemoteSystemUnavailable is the best available information that we provide about the success or failure of the request in this situation. You may be running into a known issue that we have recently fixed.  Expect a new release, containing this fix, soon.

**Comment by cmknox** [comment]
@revolutionkpi have you had a chance to test out the latest release to see if it fixes this issue?

**Comment by revolutionkpi** [comment]
I have just moved to 0.12.0 SDK and it works fine. Thanks.
