### ISSUE TITLE
Possible to keep service alive on Android->Windows scenario?

### ISSUE THREAD

**Issue by MahdiGhiasi** [Microsoft/project-rome#33]
On Windows to Windows scenario, the app service on the destination device will continue to be alive as long as the source device wants (keeps the connection object alive).

However, on Android to Windows scenario it seems that the app service on the Windows device gets cancelled after ~30 seconds by `SystemPolicy`.

Is there any way to keep the service alive for more time, just like Windows to Windows scenario?

**Comment by bviglietta** [comment]
The background task that hosts a remote app service on Windows gets to run for 30 seconds before the system will terminate it. You can extend its lifetime somewhat by acquiring a [deferral](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.background.ibackgroundtaskinstance.getdeferral#Windows_ApplicationModel_Background_IBackgroundTaskInstance_GetDeferral), but it's still not indefinite.

In short, you can't rely on a remote app service connection to be long-lived, and you have to be prepared to reopen it as necessary.

I would expect the lifetime behavior to be the same between remote Windows->Windows calls and remote Android->Windows calls. If, on the other hand, you're doing a _local_ app service call on Windows, the system may be able to tie the lifetime of the app service to the lifetime of the caller.
