### ISSUE TITLE
What is the compatibility of Project Rome for Android with graddle?

### ISSUE THREAD

**Issue by IoniCStorM** [Microsoft/project-rome#37]
I was trying with graddle 3.0 and keep failing with error "unable to merge dex". I saw all the samples are using graddle 2.2.0, is there a compatibility issue with Project Rome at the moment? And is there plan to support higher version?

Thanks,

**Comment by cmknox** [comment]
@IoniCStorM that is correct, currently this project is only supporting gradle 2.2.0.  However, there are plans to support a newer version in a future release.

**Comment by IoniCStorM** [comment]
Thanks for the reply, was this documented (or noted) somewhere? If not, it would be nice to add this onto the ReadMe of the Android folder.

**Comment by cmknox** [comment]
@IoniCStorM You are right, I will get that added, thanks for the feedback.
