### ISSUE TITLE
Gettig SessionLimitsExceeded

### ISSUE THREAD

**Issue by miker1423** [Microsoft/project-rome#44]
Hello, I've been playing around with the API on the UWP platform, when running on my laptop or tablet, it can create remote sessions and discover other remote sessions, but when running on my phone it doesn't work, when creating a new remote session it always has a RemoteSystemSessionCreationStatus.SessionLimitsExceeded, and even if I create the session from my laptop and my tablet can find it, my phone can't. Any idea why? My win10 mobile build is 10.0.15254.124 and the version is 1709.

**Comment by cmknox** [comment]
@miker1423 this is by design behavior unfortunately.  The Windows mobile build is running against RS2, where Remote Sessions were disabled.  Remote Sessions were first available in RS3.  At this point, the mobile builds are only getting servicing updates as needed.

**Comment by miker1423** [comment]
Great, thanks! And when is the RS3 expected? Or is it the next big update of Windows?

**Comment by MahdiGhiasi** [comment]
@miker1423 Windows mobile won't get new builds (RS3+) ever afaik.
