### ISSUE TITLE
Bad request on MS Graph

### ISSUE THREAD

**Issue by cansado2930** [Microsoft/project-rome#51]
Hi,
I have tried to use MS Graph because I wish I use it on Xamarin Forms and... I couldn't get it works. I want to read available devices and send command. I received bad request. Could you tell me some advice in order to implement it? I get the token with the SDK c# that I use in order to get information about account, so the token works. But I don't know what I have been able to do bad… 
Thank you

**Comment by sphenry** [comment]
First of all make, sure you are requesting the right OAuth scopes. Listing and commanding devices requires: 'Device.Read' and 'Device.Command'. Reading and writing activities need 'UserActivity.ReadWrite.CreatedByApp'

A good place to play with the Microsoft Graph APIs is here:
https://developer.microsoft.com/en-us/graph/graph-explorer?request=me/devices&method=GET&version=beta&GraphUrl=https://graph.microsoft.com

**Comment by cansado2930** [comment]
Thank @sphenry I didn't know the MS Graph explorer, it is very great! with your sample I have found the problem, I set on the url 1.0 instead beta. 
Again, very thanks you!!
