### ISSUE TITLE
libgnustl_shared.so conflicts with Spotify SDK

### ISSUE THREAD

**Issue by delfinof** [Microsoft/project-rome#6]
The version of the libgnustl_shared.so is in conflict with the one shipped by the Spotify SDK, available here;
      https://github.com/spotify/android-sdk/releases/tag/24-noconnect-2.20b

Since yours size is 5MB vs 1MB Spotify's version, my guess is that they are stripping something: while giving priority to your version seems to allow Spotify SDK to work correctly, the other way round makes the app to crash in your native code for the luck of some symbols.

In order to avoid possible unknown bugs (and conflicts with other SDKs), wouldn't it be better to just use static linking?
If it's a licensing issue, wouldn't be better to rename your version like libgnustl_rome_shared.so?

**Comment by cmknox** [comment]
Thanks for the feedback.  I've added this as a potential enhancement for a future release.
