### ISSUE TITLE
RemoteSystemSessionCreationStatus.SessionLimitsExceeded

### ISSUE THREAD

**Issue by SeanGahan** [Microsoft/project-rome#60]
Not an issue yet; I can't find documentation for the connection limit.  I'd like to use RemoteSystems for messaging on IOT devices in our manufacturing plant, but before I spend a ton of time I'd like to know what the limit is.  Does anyone know what the limit is?

Thanks!

**Comment by cmknox** [comment]
@SeanGahan I do not believe there is a connection limit.  The maximum number of sessions that can be hosted is 255.

**Comment by SeanGahan** [comment]
@cmknox Thanks for the reply!
