### ISSUE TITLE
Non-public API usage detected by the App Store Team

### ISSUE THREAD

**Issue by revolutionkpi** [Microsoft/project-rome#68]
I was publishing an app that uses ProjectRomeSdk pod with version 0.12 and got an error from ITunerConnect:

Non-public API usage:

The app references non-public symbols in Frameworks/ConnectedDevices.framework/ConnectedDevices: _getcontext, _makecontext, _setcontext

Could you investigate and fix this issue?

Thanks in advance.

**Comment by nathpete-msft** [comment]
Thanks for letting us know about this, and sorry we didn't catch it earlier!
The good news is that this issue should be resolved as of the 0.13.7 release 😄.

Closing, but please re-open if you still happen to hit any similar issues on 0.13.7+.
