### ISSUE TITLE
Fails to build ConnectedDevices.Xamarin.Droid

### ISSUE THREAD

**Issue by pnp0a03** [Microsoft/project-rome#7]
Hi,
I could not build the ConnectedDevices.Xamarin.Droid with following errors.
Do you have any clue for build it?
...If the latest binaries are uploaded as nuget, it helps me too :) 

Source:  https://github.com/Microsoft/project-rome/commit/8960cb13c0508accde90e222f4b2a3a04b099565
Tools: Visual Studio 2017 Enterprise 26228.9
```
1>D:\Github\project-rome\xamarin\src\ConnectedDevices.Xamarin.Droid\Additions\Platform.cs(58,33,58,61): error CS0246: The type or namespace name 'PlatformInitializationStatus' could not be found (are you missing a using directive or an assembly reference?)
1>D:\Github\project-rome\xamarin\src\ConnectedDevices.Xamarin.Droid\Additions\Platform.cs(49,64,49,94): error CS0535: 'Platform.PlatformInitializer' does not implement interface member 'IPlatformInitializationHandler.OnDone(bool)'
```

**Comment by anpea** [comment]
Hi,

This looks to be a issue that has now been resolved; a mismatch in our internal API call. Make sure you have the latest version of our Xamarin deployment (0.2.0) and let us know if this issue still persists.

Thanks

**Comment by pnp0a03** [comment]
I could succeeded to build the sample app with new 0.2.0 nuget package. Thank you!
[Microsoft.ConnectedDevices.Xamarin.Droid 0.2.0 ](https://www.nuget.org/packages/Microsoft.ConnectedDevices.Xamarin.Droid/)
..But I'm faced in another runtime exception and It fails to get the list of remote devices :) I'll open new issue for the one.
