### ISSUE TITLE
UWP Sample and Microsoft.ConnectedDevices.UserNotifications.Uwp NuGet

### ISSUE THREAD

**Issue by wjvii** [Microsoft/project-rome#71]
I downloaded the project-rome-release-0.13.7 samples and when I look at the NuGet packages it says Not available in this source for the nuget package Microsoft.ConnectedDevices.UserNotifications.Uwp. Can someone tell me what package source I need to setup in order to be able to find this package? Thank you in advance.

**Comment by usvoyager** [comment]
Please get the nuget package 'Microsoft.ConnectedDevices.UserNotifications' instead. Sorry for the typo in the sample.

**Comment by bbowman** [comment]
I believe this is resolved with the 1.0.0 samples. Please reopen if you are still having issues building the samples.
