### ISSUE TITLE
Build error, because 'Secrets' and ProdClientId' value is not defined in source.

### ISSUE THREAD

**Issue by wonsik-song** [Microsoft/project-rome#72]
Hi,
I try to build GraphNotificationSample in Window.
But build error occurs, because 'Secrets' and ProdClientId' value is not defined in source.
Anyone can help me to solve this issue.
Thanks

**Comment by bbowman** [comment]
Closing this since I believe this should work for you. Please reopen if you are still seeing issues building the samples.
