### ISSUE TITLE
Empty android device name shown in other devices.

### ISSUE THREAD

**Issue by mghiasi75** [Microsoft/project-rome#8]
In Xamarin (Android) sample, after authentication, the android device will appear in devices list in Windows devices with same MSA account (when querying Windows Rome APIs). But it has an **empty** DisplayName.

I'm testing sample on a Nexus 4 running Android 5.1.1.

Is that the expected behavior?

**Comment by ajpeacock0** [comment]
Android devices are not supported as devices to connect to, and so should be filtered out by the app. This can be done by filtering out RemoteSystemKinds.Unknown.

Future Windows releases will not return Android devices until Android has the capability to be connected to.

**Comment by mghiasi75** [comment]
Thanks.
